export const theme = {
  primaryColor: ' #212121',
  secondaryColor: '#424242',
  backgroundColor: '#121212',
  hoverColor: '#616161',
  textPrimary: '#bdbdbd',
  textSecondary: '#fafafa',
  textAccent: '#ff4757',
  textLight: '#b6b6b8',
  maxWidth: '1800px',
  breakpoints: {
    fold: 'screen and (max-width:280px)',
    iphone: 'screen and (max-width:320px)',
    mobile: 'screen and (max-width:375px)',
    xsm: 'screen and (max-width:414px)',
    sm: 'screen and (max-width:640px)',
    md: 'screen and (max-width:768px)',
    minMd: 'screen and (min-width:769px)',
    lg: 'screen and (max-width:1024px)',
    xl: 'screen and (max-width:1280px)',
    height: 'screen and (min-height:1200px)',
  },
};
